// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sticker_buffer.proto

package com.google.mediapipe.apps.instantmotiontracking;

public final class StickerBuffer {
  private StickerBuffer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StickerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:instantmotiontracking.Sticker)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>required float x = 2;</code>
     * @return Whether the x field is set.
     */
    boolean hasX();
    /**
     * <code>required float x = 2;</code>
     * @return The x.
     */
    float getX();

    /**
     * <code>required float y = 3;</code>
     * @return Whether the y field is set.
     */
    boolean hasY();
    /**
     * <code>required float y = 3;</code>
     * @return The y.
     */
    float getY();

    /**
     * <code>required float rotation = 4;</code>
     * @return Whether the rotation field is set.
     */
    boolean hasRotation();
    /**
     * <code>required float rotation = 4;</code>
     * @return The rotation.
     */
    float getRotation();

    /**
     * <code>required float scale = 5;</code>
     * @return Whether the scale field is set.
     */
    boolean hasScale();
    /**
     * <code>required float scale = 5;</code>
     * @return The scale.
     */
    float getScale();

    /**
     * <code>required int32 renderID = 6;</code>
     * @return Whether the renderID field is set.
     */
    boolean hasRenderID();
    /**
     * <code>required int32 renderID = 6;</code>
     * @return The renderID.
     */
    int getRenderID();
  }
  /**
   * Protobuf type {@code instantmotiontracking.Sticker}
   */
  public  static final class Sticker extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:instantmotiontracking.Sticker)
      StickerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Sticker.newBuilder() to construct.
    private Sticker(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Sticker() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Sticker();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Sticker(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              x_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              y_ = input.readFloat();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              rotation_ = input.readFloat();
              break;
            }
            case 45: {
              bitField0_ |= 0x00000010;
              scale_ = input.readFloat();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              renderID_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.internal_static_instantmotiontracking_Sticker_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.internal_static_instantmotiontracking_Sticker_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker.class, com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     * @return Whether the id field is set.
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 id = 1;</code>
     * @return The id.
     */
    public int getId() {
      return id_;
    }

    public static final int X_FIELD_NUMBER = 2;
    private float x_;
    /**
     * <code>required float x = 2;</code>
     * @return Whether the x field is set.
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required float x = 2;</code>
     * @return The x.
     */
    public float getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 3;
    private float y_;
    /**
     * <code>required float y = 3;</code>
     * @return Whether the y field is set.
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required float y = 3;</code>
     * @return The y.
     */
    public float getY() {
      return y_;
    }

    public static final int ROTATION_FIELD_NUMBER = 4;
    private float rotation_;
    /**
     * <code>required float rotation = 4;</code>
     * @return Whether the rotation field is set.
     */
    public boolean hasRotation() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required float rotation = 4;</code>
     * @return The rotation.
     */
    public float getRotation() {
      return rotation_;
    }

    public static final int SCALE_FIELD_NUMBER = 5;
    private float scale_;
    /**
     * <code>required float scale = 5;</code>
     * @return Whether the scale field is set.
     */
    public boolean hasScale() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required float scale = 5;</code>
     * @return The scale.
     */
    public float getScale() {
      return scale_;
    }

    public static final int RENDERID_FIELD_NUMBER = 6;
    private int renderID_;
    /**
     * <code>required int32 renderID = 6;</code>
     * @return Whether the renderID field is set.
     */
    public boolean hasRenderID() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>required int32 renderID = 6;</code>
     * @return The renderID.
     */
    public int getRenderID() {
      return renderID_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRotation()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasScale()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRenderID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeFloat(2, x_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeFloat(3, y_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeFloat(4, rotation_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeFloat(5, scale_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeInt32(6, renderID_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, x_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, y_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, rotation_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, scale_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, renderID_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker)) {
        return super.equals(obj);
      }
      com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker other = (com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker) obj;

      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (getId()
            != other.getId()) return false;
      }
      if (hasX() != other.hasX()) return false;
      if (hasX()) {
        if (java.lang.Float.floatToIntBits(getX())
            != java.lang.Float.floatToIntBits(
                other.getX())) return false;
      }
      if (hasY() != other.hasY()) return false;
      if (hasY()) {
        if (java.lang.Float.floatToIntBits(getY())
            != java.lang.Float.floatToIntBits(
                other.getY())) return false;
      }
      if (hasRotation() != other.hasRotation()) return false;
      if (hasRotation()) {
        if (java.lang.Float.floatToIntBits(getRotation())
            != java.lang.Float.floatToIntBits(
                other.getRotation())) return false;
      }
      if (hasScale() != other.hasScale()) return false;
      if (hasScale()) {
        if (java.lang.Float.floatToIntBits(getScale())
            != java.lang.Float.floatToIntBits(
                other.getScale())) return false;
      }
      if (hasRenderID() != other.hasRenderID()) return false;
      if (hasRenderID()) {
        if (getRenderID()
            != other.getRenderID()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasX()) {
        hash = (37 * hash) + X_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getX());
      }
      if (hasY()) {
        hash = (37 * hash) + Y_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getY());
      }
      if (hasRotation()) {
        hash = (37 * hash) + ROTATION_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getRotation());
      }
      if (hasScale()) {
        hash = (37 * hash) + SCALE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getScale());
      }
      if (hasRenderID()) {
        hash = (37 * hash) + RENDERID_FIELD_NUMBER;
        hash = (53 * hash) + getRenderID();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code instantmotiontracking.Sticker}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:instantmotiontracking.Sticker)
        com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.internal_static_instantmotiontracking_Sticker_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.internal_static_instantmotiontracking_Sticker_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker.class, com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker.Builder.class);
      }

      // Construct using com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        rotation_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        scale_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000010);
        renderID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.internal_static_instantmotiontracking_Sticker_descriptor;
      }

      @java.lang.Override
      public com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker getDefaultInstanceForType() {
        return com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker.getDefaultInstance();
      }

      @java.lang.Override
      public com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker build() {
        com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker buildPartial() {
        com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker result = new com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.x_ = x_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.y_ = y_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.rotation_ = rotation_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.scale_ = scale_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.renderID_ = renderID_;
          to_bitField0_ |= 0x00000020;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker) {
          return mergeFrom((com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker other) {
        if (other == com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasRotation()) {
          setRotation(other.getRotation());
        }
        if (other.hasScale()) {
          setScale(other.getScale());
        }
        if (other.hasRenderID()) {
          setRenderID(other.getRenderID());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasX()) {
          return false;
        }
        if (!hasY()) {
          return false;
        }
        if (!hasRotation()) {
          return false;
        }
        if (!hasScale()) {
          return false;
        }
        if (!hasRenderID()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       * @return Whether the id field is set.
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 id = 1;</code>
       * @return The id.
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private float x_ ;
      /**
       * <code>required float x = 2;</code>
       * @return Whether the x field is set.
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required float x = 2;</code>
       * @return The x.
       */
      public float getX() {
        return x_;
      }
      /**
       * <code>required float x = 2;</code>
       * @param value The x to set.
       * @return This builder for chaining.
       */
      public Builder setX(float value) {
        bitField0_ |= 0x00000002;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float x = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000002);
        x_ = 0F;
        onChanged();
        return this;
      }

      private float y_ ;
      /**
       * <code>required float y = 3;</code>
       * @return Whether the y field is set.
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required float y = 3;</code>
       * @return The y.
       */
      public float getY() {
        return y_;
      }
      /**
       * <code>required float y = 3;</code>
       * @param value The y to set.
       * @return This builder for chaining.
       */
      public Builder setY(float value) {
        bitField0_ |= 0x00000004;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float y = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000004);
        y_ = 0F;
        onChanged();
        return this;
      }

      private float rotation_ ;
      /**
       * <code>required float rotation = 4;</code>
       * @return Whether the rotation field is set.
       */
      public boolean hasRotation() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required float rotation = 4;</code>
       * @return The rotation.
       */
      public float getRotation() {
        return rotation_;
      }
      /**
       * <code>required float rotation = 4;</code>
       * @param value The rotation to set.
       * @return This builder for chaining.
       */
      public Builder setRotation(float value) {
        bitField0_ |= 0x00000008;
        rotation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float rotation = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearRotation() {
        bitField0_ = (bitField0_ & ~0x00000008);
        rotation_ = 0F;
        onChanged();
        return this;
      }

      private float scale_ ;
      /**
       * <code>required float scale = 5;</code>
       * @return Whether the scale field is set.
       */
      public boolean hasScale() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required float scale = 5;</code>
       * @return The scale.
       */
      public float getScale() {
        return scale_;
      }
      /**
       * <code>required float scale = 5;</code>
       * @param value The scale to set.
       * @return This builder for chaining.
       */
      public Builder setScale(float value) {
        bitField0_ |= 0x00000010;
        scale_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float scale = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearScale() {
        bitField0_ = (bitField0_ & ~0x00000010);
        scale_ = 0F;
        onChanged();
        return this;
      }

      private int renderID_ ;
      /**
       * <code>required int32 renderID = 6;</code>
       * @return Whether the renderID field is set.
       */
      public boolean hasRenderID() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>required int32 renderID = 6;</code>
       * @return The renderID.
       */
      public int getRenderID() {
        return renderID_;
      }
      /**
       * <code>required int32 renderID = 6;</code>
       * @param value The renderID to set.
       * @return This builder for chaining.
       */
      public Builder setRenderID(int value) {
        bitField0_ |= 0x00000020;
        renderID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 renderID = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearRenderID() {
        bitField0_ = (bitField0_ & ~0x00000020);
        renderID_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:instantmotiontracking.Sticker)
    }

    // @@protoc_insertion_point(class_scope:instantmotiontracking.Sticker)
    private static final com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker();
    }

    public static com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Sticker>
        PARSER = new com.google.protobuf.AbstractParser<Sticker>() {
      @java.lang.Override
      public Sticker parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Sticker(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Sticker> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Sticker> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StickerRollOrBuilder extends
      // @@protoc_insertion_point(interface_extends:instantmotiontracking.StickerRoll)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .instantmotiontracking.Sticker sticker = 1;</code>
     */
    java.util.List<com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker>
        getStickerList();
    /**
     * <code>repeated .instantmotiontracking.Sticker sticker = 1;</code>
     */
    com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker getSticker(int index);
    /**
     * <code>repeated .instantmotiontracking.Sticker sticker = 1;</code>
     */
    int getStickerCount();
    /**
     * <code>repeated .instantmotiontracking.Sticker sticker = 1;</code>
     */
    java.util.List<? extends com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerOrBuilder>
        getStickerOrBuilderList();
    /**
     * <code>repeated .instantmotiontracking.Sticker sticker = 1;</code>
     */
    com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerOrBuilder getStickerOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code instantmotiontracking.StickerRoll}
   */
  public  static final class StickerRoll extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:instantmotiontracking.StickerRoll)
      StickerRollOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StickerRoll.newBuilder() to construct.
    private StickerRoll(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StickerRoll() {
      sticker_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StickerRoll();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StickerRoll(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                sticker_ = new java.util.ArrayList<com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker>();
                mutable_bitField0_ |= 0x00000001;
              }
              sticker_.add(
                  input.readMessage(com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          sticker_ = java.util.Collections.unmodifiableList(sticker_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.internal_static_instantmotiontracking_StickerRoll_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.internal_static_instantmotiontracking_StickerRoll_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRoll.class, com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRoll.Builder.class);
    }

    public static final int STICKER_FIELD_NUMBER = 1;
    private java.util.List<com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker> sticker_;
    /**
     * <code>repeated .instantmotiontracking.Sticker sticker = 1;</code>
     */
    public java.util.List<com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker> getStickerList() {
      return sticker_;
    }
    /**
     * <code>repeated .instantmotiontracking.Sticker sticker = 1;</code>
     */
    public java.util.List<? extends com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerOrBuilder>
        getStickerOrBuilderList() {
      return sticker_;
    }
    /**
     * <code>repeated .instantmotiontracking.Sticker sticker = 1;</code>
     */
    public int getStickerCount() {
      return sticker_.size();
    }
    /**
     * <code>repeated .instantmotiontracking.Sticker sticker = 1;</code>
     */
    public com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker getSticker(int index) {
      return sticker_.get(index);
    }
    /**
     * <code>repeated .instantmotiontracking.Sticker sticker = 1;</code>
     */
    public com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerOrBuilder getStickerOrBuilder(
        int index) {
      return sticker_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getStickerCount(); i++) {
        if (!getSticker(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < sticker_.size(); i++) {
        output.writeMessage(1, sticker_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < sticker_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, sticker_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRoll)) {
        return super.equals(obj);
      }
      com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRoll other = (com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRoll) obj;

      if (!getStickerList()
          .equals(other.getStickerList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getStickerCount() > 0) {
        hash = (37 * hash) + STICKER_FIELD_NUMBER;
        hash = (53 * hash) + getStickerList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRoll parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRoll parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRoll parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRoll parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRoll parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRoll parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRoll parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRoll parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRoll parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRoll parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRoll parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRoll parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRoll prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code instantmotiontracking.StickerRoll}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:instantmotiontracking.StickerRoll)
        com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRollOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.internal_static_instantmotiontracking_StickerRoll_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.internal_static_instantmotiontracking_StickerRoll_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRoll.class, com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRoll.Builder.class);
      }

      // Construct using com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRoll.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getStickerFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (stickerBuilder_ == null) {
          sticker_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          stickerBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.internal_static_instantmotiontracking_StickerRoll_descriptor;
      }

      @java.lang.Override
      public com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRoll getDefaultInstanceForType() {
        return com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRoll.getDefaultInstance();
      }

      @java.lang.Override
      public com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRoll build() {
        com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRoll result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRoll buildPartial() {
        com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRoll result = new com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRoll(this);
        int from_bitField0_ = bitField0_;
        if (stickerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            sticker_ = java.util.Collections.unmodifiableList(sticker_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.sticker_ = sticker_;
        } else {
          result.sticker_ = stickerBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRoll) {
          return mergeFrom((com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRoll)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRoll other) {
        if (other == com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRoll.getDefaultInstance()) return this;
        if (stickerBuilder_ == null) {
          if (!other.sticker_.isEmpty()) {
            if (sticker_.isEmpty()) {
              sticker_ = other.sticker_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureStickerIsMutable();
              sticker_.addAll(other.sticker_);
            }
            onChanged();
          }
        } else {
          if (!other.sticker_.isEmpty()) {
            if (stickerBuilder_.isEmpty()) {
              stickerBuilder_.dispose();
              stickerBuilder_ = null;
              sticker_ = other.sticker_;
              bitField0_ = (bitField0_ & ~0x00000001);
              stickerBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getStickerFieldBuilder() : null;
            } else {
              stickerBuilder_.addAllMessages(other.sticker_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        for (int i = 0; i < getStickerCount(); i++) {
          if (!getSticker(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRoll parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRoll) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker> sticker_ =
        java.util.Collections.emptyList();
      private void ensureStickerIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          sticker_ = new java.util.ArrayList<com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker>(sticker_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker, com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker.Builder, com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerOrBuilder> stickerBuilder_;

      /**
       * <code>repeated .instantmotiontracking.Sticker sticker = 1;</code>
       */
      public java.util.List<com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker> getStickerList() {
        if (stickerBuilder_ == null) {
          return java.util.Collections.unmodifiableList(sticker_);
        } else {
          return stickerBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .instantmotiontracking.Sticker sticker = 1;</code>
       */
      public int getStickerCount() {
        if (stickerBuilder_ == null) {
          return sticker_.size();
        } else {
          return stickerBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .instantmotiontracking.Sticker sticker = 1;</code>
       */
      public com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker getSticker(int index) {
        if (stickerBuilder_ == null) {
          return sticker_.get(index);
        } else {
          return stickerBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .instantmotiontracking.Sticker sticker = 1;</code>
       */
      public Builder setSticker(
          int index, com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker value) {
        if (stickerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStickerIsMutable();
          sticker_.set(index, value);
          onChanged();
        } else {
          stickerBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .instantmotiontracking.Sticker sticker = 1;</code>
       */
      public Builder setSticker(
          int index, com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker.Builder builderForValue) {
        if (stickerBuilder_ == null) {
          ensureStickerIsMutable();
          sticker_.set(index, builderForValue.build());
          onChanged();
        } else {
          stickerBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .instantmotiontracking.Sticker sticker = 1;</code>
       */
      public Builder addSticker(com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker value) {
        if (stickerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStickerIsMutable();
          sticker_.add(value);
          onChanged();
        } else {
          stickerBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .instantmotiontracking.Sticker sticker = 1;</code>
       */
      public Builder addSticker(
          int index, com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker value) {
        if (stickerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStickerIsMutable();
          sticker_.add(index, value);
          onChanged();
        } else {
          stickerBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .instantmotiontracking.Sticker sticker = 1;</code>
       */
      public Builder addSticker(
          com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker.Builder builderForValue) {
        if (stickerBuilder_ == null) {
          ensureStickerIsMutable();
          sticker_.add(builderForValue.build());
          onChanged();
        } else {
          stickerBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .instantmotiontracking.Sticker sticker = 1;</code>
       */
      public Builder addSticker(
          int index, com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker.Builder builderForValue) {
        if (stickerBuilder_ == null) {
          ensureStickerIsMutable();
          sticker_.add(index, builderForValue.build());
          onChanged();
        } else {
          stickerBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .instantmotiontracking.Sticker sticker = 1;</code>
       */
      public Builder addAllSticker(
          java.lang.Iterable<? extends com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker> values) {
        if (stickerBuilder_ == null) {
          ensureStickerIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, sticker_);
          onChanged();
        } else {
          stickerBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .instantmotiontracking.Sticker sticker = 1;</code>
       */
      public Builder clearSticker() {
        if (stickerBuilder_ == null) {
          sticker_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          stickerBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .instantmotiontracking.Sticker sticker = 1;</code>
       */
      public Builder removeSticker(int index) {
        if (stickerBuilder_ == null) {
          ensureStickerIsMutable();
          sticker_.remove(index);
          onChanged();
        } else {
          stickerBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .instantmotiontracking.Sticker sticker = 1;</code>
       */
      public com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker.Builder getStickerBuilder(
          int index) {
        return getStickerFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .instantmotiontracking.Sticker sticker = 1;</code>
       */
      public com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerOrBuilder getStickerOrBuilder(
          int index) {
        if (stickerBuilder_ == null) {
          return sticker_.get(index);  } else {
          return stickerBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .instantmotiontracking.Sticker sticker = 1;</code>
       */
      public java.util.List<? extends com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerOrBuilder>
           getStickerOrBuilderList() {
        if (stickerBuilder_ != null) {
          return stickerBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(sticker_);
        }
      }
      /**
       * <code>repeated .instantmotiontracking.Sticker sticker = 1;</code>
       */
      public com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker.Builder addStickerBuilder() {
        return getStickerFieldBuilder().addBuilder(
            com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker.getDefaultInstance());
      }
      /**
       * <code>repeated .instantmotiontracking.Sticker sticker = 1;</code>
       */
      public com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker.Builder addStickerBuilder(
          int index) {
        return getStickerFieldBuilder().addBuilder(
            index, com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker.getDefaultInstance());
      }
      /**
       * <code>repeated .instantmotiontracking.Sticker sticker = 1;</code>
       */
      public java.util.List<com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker.Builder>
           getStickerBuilderList() {
        return getStickerFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker, com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker.Builder, com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerOrBuilder>
          getStickerFieldBuilder() {
        if (stickerBuilder_ == null) {
          stickerBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker, com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.Sticker.Builder, com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerOrBuilder>(
                  sticker_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          sticker_ = null;
        }
        return stickerBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:instantmotiontracking.StickerRoll)
    }

    // @@protoc_insertion_point(class_scope:instantmotiontracking.StickerRoll)
    private static final com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRoll DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRoll();
    }

    public static com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRoll getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<StickerRoll>
        PARSER = new com.google.protobuf.AbstractParser<StickerRoll>() {
      @java.lang.Override
      public StickerRoll parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StickerRoll(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StickerRoll> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StickerRoll> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.mediapipe.apps.instantmotiontracking.StickerBuffer.StickerRoll getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_instantmotiontracking_Sticker_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_instantmotiontracking_Sticker_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_instantmotiontracking_StickerRoll_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_instantmotiontracking_StickerRoll_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024sticker_buffer.proto\022\025instantmotiontra" +
      "cking\"^\n\007Sticker\022\n\n\002id\030\001 \002(\005\022\t\n\001x\030\002 \002(\002\022" +
      "\t\n\001y\030\003 \002(\002\022\020\n\010rotation\030\004 \002(\002\022\r\n\005scale\030\005 " +
      "\002(\002\022\020\n\010renderID\030\006 \002(\005\">\n\013StickerRoll\022/\n\007" +
      "sticker\030\001 \003(\0132\036.instantmotiontracking.St" +
      "ickerB1\n/com.google.mediapipe.apps.insta" +
      "ntmotiontracking"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_instantmotiontracking_Sticker_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_instantmotiontracking_Sticker_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_instantmotiontracking_Sticker_descriptor,
        new java.lang.String[] { "Id", "X", "Y", "Rotation", "Scale", "RenderID", });
    internal_static_instantmotiontracking_StickerRoll_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_instantmotiontracking_StickerRoll_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_instantmotiontracking_StickerRoll_descriptor,
        new java.lang.String[] { "Sticker", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
